app/app/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'app.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'hack.views.signup', name='signup'),
    
    url('^register/', CreateView.as_view(
            template_name='register.html',
            form_class=UserCreationForm,
            success_url='hack.creat'
    ), name='registerPage'),
    # url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'login.html'}),

    url(r'^login/','hack.views.login', name='login'),
    url(r'^signin/','hack.views.signin', name='signin'),
    url(r'^authenticateUser/','hack.views.authenticateUser', name='authenticateUser'),
    url(r'^notify/','hack.views.notify', name='notify'),
    url(r'^sendNotification/','hack.views.sendNotification', name='sendNotification'),
    url(r'^addNumbers/','hack.views.addNumbers', name='addNumbers'),
    url(r'^logoutUser/','hack.views.logoutUser', name='logoutUser'),
    url(r'^base/','hack.views.base', name='base'),
    url(r'^addDetailsToDB/','hack.views.addDetailsToDB', name='addDetailsToDB'),
    url(r'^addClass/', 'hack.views.addClass', name='addClass'),
    url(r'^userFeed/', 'hack.views.userFeed', name='userFeed'),
    url(r'^searchFeed/', 'hack.views.searchFeed', name='searchFeed')

# )

)
# url(r'^accounts/login/$', auth_views.login, {'template_name': 'myapp/login.html'}),

app/hack/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



class StudentInfo(models.Model):
	number = models.IntegerField(default=0)
	email = models.CharField(max_length=200)

	def __unicode__(self):
		return self.email



class AddClass(models.Model):
	class_name = models.CharField(max_length=200)
	students = models.ManyToManyField(StudentInfo, null=True)



	def __unicode__(self):
		return self.class_name



class Notification(models.Model):
	class_name = models.CharField(max_length=50)
	timeStamp = models.CharField(max_length=50)
	note = models.CharField(max_length=300)

app/hack/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(max_length=20)
	# password = forms.PasswordInput()
	password = forms.CharField(label=("Password"), widget=forms.PasswordInput, required=False)


class StudentDetails(forms.Form):
	phoneNumbers = forms.CharField(widget=forms.Textarea)
	emails = forms.CharField(widget=forms.Textarea)
	className = forms.CharField(max_length=20)

class SendNotification(forms.Form):
	class_name=forms.CharField(widget=forms.TextInput(attrs={'class' : 'btn-selector'}))
	note = forms.CharField(widget=forms.Textarea)

class SearchFeedForm(forms.Form):
	className = forms.CharField(max_length=20)

app/hack/views.py
import pdb
from forms import *
from models import *
from send_sms import sendMessage
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as djangoLogin
import pdb
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_protect
from forms import *
from send_email import send_email
import datetime

def signup(request):
	return render(request, "signup.html")

def login(request):
	username = str(request.POST.get('username'))
	password1 = str(request.POST.get('password1'))
	password2 = str(request.POST.get('password2'))


	#Case passwords does not match
	if password1 != password2:
		return render(request, 'register.html', {'msg':'Passwords not match', 'form':UserCreationForm()})
	
	#Create user
	else:
		user = User.objects.create_user(username=username, password=password1)
		user.save()
	
	return render(request, 'signin.html', {'form':LoginForm})



def signin(request):
	"""
	Redirects the user to the login form
	"""
	form = LoginForm()
	return render(request, 'signin.html', {'form':form})


@csrf_protect
def authenticateUser(request):
	"""
	This view authenticate the user and redirects him to the control panel
	"""
	username = str(request.POST.get('username'))
	password = str(request.POST.get('password'))
	
	user = authenticate(username=username, password=password)
	if user is not None:
		djangoLogin(request, user)
		
		# return render(request, 'addclass.html',{'user':user, 'returnlist': AddClass.objects.all()})
		return redirect('/addClass', {'form':LoginForm(), 'msg':'Incorrect username or password'})

	#Case username and password are incorrect
	else:
		return render(request, 'signin.html', {'form':LoginForm(), 'msg':'Incorrect username or password'})
		


@csrf_protect
def notify(request):
	if request.user.is_authenticated():
		return render(request, 'notify.html', {'form':StudentDetails(), 'notifyForm':SendNotification()})


@csrf_protect
def sendNotification(request):
	if request.user.is_authenticated():
		# pdb.set_trace()

		className = str(request.POST.get('class_name'))
		note = request.POST.get('note')

		subject = "{cn} is canceled".format(cn=className)
		msg_body = 'Dear students, our class is canceled.\n\n\n{note}'.format(note=note)
		recipient = AddClass.objects.filter(class_name=className)[0].students
	
		notif = Notification()
		notif.class_name = className
		notif.timeStamp = datetime.datetime.now().strftime("%A, %d. %B %Y %I:%M %p")
		notif.note=note
		notif.save()

		for rec in recipient.all():
			send_email(subject, msg_body, str(rec.email))	
			sendMessage(className, rec.number)


		# return render(request, 'notify.html', {"notifyMsg":"Messages sent successfully."})
		return render(request, 'addclass.html',{'user':request.user, 'returnlist': AddClass.objects.all(), 'studentDetailsForm':StudentDetails(), 'notifyForm':SendNotification(), "notifyMessage":"Messages sent successfully"})




def addNumbers(request):
	if request.user.is_authenticated():
		return render(request, 'addStudents.html')
	else:
		return render(request, 'signin.html', {'form':LoginForm()})

def logoutUser(request):
	logout(request)
	return render(request, 'signin.html', {'form':LoginForm()})

def addClass(request):
	# print "ADD NEWW CLASS PAGE"
	return render(request, 'addclass.html',{'user':request.user, 'returnlist': AddClass.objects.all(), 'studentDetailsForm':StudentDetails(), 'notifyForm':SendNotification()})


def base(request):
	return render(request, 'studentview.html' )


def addDetailsToDB(request):
	# pdb.set_trace()
	phoneNumbers = str(request.POST.get('phoneNumbers'))
	emails = request.POST.get('emails')
	className = request.POST.get('className')

	phoneNumbers = phoneNumbers.split(', ')
	emails = emails.split(', ')
	
	addClass = AddClass.objects.get_or_create(class_name=className)[0]
	
	for number, email in zip(phoneNumbers, emails):
		student = StudentInfo.objects.get_or_create(number=str(number), email=str(email))	[0]
		addClass.students.add(student)
	
	# return render(request, 'addclass.html', {'user':request.user, 'returnlist': AddClass.objects.all(), 'studentDetailsForm':StudentDetails(), "addNumbersMessage":"Numbers added successfully"})
	return redirect('/addClass', {'user':request.user, 'returnlist': AddClass.objects.all(), 'studentDetailsForm':StudentDetails(), "addNumbersMessage":"Numbers added successfully"})

def userFeed(request):
	return render(request, 'studentview.html', {'notifications':Notification.objects.all()[::-1], 'searchFeedForm':SearchFeedForm()})
		
@csrf_protect
def searchFeed(request):
	className = request.POST.get('className')
	return render(request, 'studentview.html', {'notifications':Notification.objects.filter(class_name=className)[::-1]})

app/hack/templates/addStudents.html
{% include 'base.html' %}

app/hack/templates/addclass.html
{% include 'base.html' %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="../../favicon.ico"> -->
    <title>Add Class</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap.min.css">

    <!-- Custom styles for this template -->
    <!-- <link href="{{STATIC_URL}}/css/instructor.css" rel="stylesheet"> -->
  </head>

<body>


{% if addNumbersMessage %}
<div class="alert alert-success alert-dismissable">
   <button type="button" class="close" data-dismiss="alert" 
      aria-hidden="true">
      &times;
   </button>
   {{addNumbersMessage}}
</div>
{% endif %}

{% if notifyMessage %}
<div class="alert alert-success alert-dismissable">
   <button type="button" class="close" data-dismiss="alert" 
      aria-hidden="true">
      &times;
   </button>
   {{notifyMessage}}
</div>
{% endif %}


<div style="margin-top:50px">
 <h1 style="text-align:center">List of registered classes</h1>
    <hr>
    </div>
<div style="margin-left:275px; margin-top:50px">
	<!-- <form method="POST" action="{% url 'hack.views.addClass' %}"> -->
	<!-- {% csrf_token %} -->
		<!-- <input type="submit" class="btn btn-success" id="addClassButton" value="Add New Class" style="width:700px; height:100px"/> -->
	<!-- </form> -->

    <form method="POST" action="{% url 'hack.views.addNumbers' %}">
    {% csrf_token %}
        <input type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal" id="addNumbersButton" value="Add Numbers" style="width:700px;"/>
    </form>

	<!--populate class for all classes in database, they will be buttons-->
	<div class="btn-group-vertical" role="group">
		{% for x in returnlist %}
		<!-- <a href="{%url 'notify'%}" ><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-cancel" style="width:700px; margin-top:10px">{{x}}</button></a> -->
    <form method="POST" action="{% url 'sendNotification' %}">
        {% csrf_token %}
        <button type="button" class="btn-selector btn btn-primary" data-toggle="modal" data-target="#notifyModal" style="width:700px; margin-top:10px">{{x}}</button></a>
    </form>
		{% endfor %}
	</div>

    </div>






<!-- ADD NUMBERS MODAL -->
    <form method='POST' action="{% url 'addDetailsToDB' %}">
    {%csrf_token %}
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Student Details</h4>
                </div>
                <div class="modal-body">
                <table>
                <tr>
                <td>
                Class Name:
                </td>
                <td>
                {{studentDetailsForm.className}}
                </td>
                <tr>
                <td>
                    <h5>Phone Numbers:</h5>
                    {{studentDetailsForm.phoneNumbers}}
                </td>
                <td style="margin-left:50px">
                    <h5>Emails:</h5>
                    {{studentDetailsForm.emails}}
                    </td>
                    </tr>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save Numbers</button>
                </div>
            </div>
        </div>
    </div>
    </form>
    <!-- END OF END NUMBERS MODAL -->


    <!-- NOTIFY MODAL -->
    <form method='POST' action="{% url 'sendNotification' %}">
    {%csrf_token %}
    <div class="modal fade" id="notifyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Student Details</h4>
                </div>
                <div class="modal-body">
                <table>
                <tr>
                <td>
                Class:
                <!-- </td> -->
                <!-- <td> -->
                
                <!-- <input type="text" disabled="disabled" style="margin-left:10px" value="22"id="classLabel"/> -->
                {{notifyForm.class_name}}
                
                </td>
                <tr>
                <td>
                    <h5 style="padding-left:150px">Note:</h5>
                </td>
                </tr>
                <tr>
                <td style="padding-left:150px">
                {{notifyForm.note}}
                </td>
                </tr>
                </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Send Notification</button>
                </div>
            </div>
        </div>
    </div>
    </form>
    <!-- END OF NOTIFY MODAL -->


<script>
    $(document).ready(function(){
        $('.btn-selector').bind('click',function(){
            $('#id_class_name').val($(this).text())
            
        })

    });


</script>

</body>
</html>

app/hack/templates/base.html
<!DOCTYPE html>
  <html lang="en">
    <head>
      <title> Is It Cancelled</title>
    </head>
    <script type="text/javascript" src="{{STATIC_URL}}jquery/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>
    
    
    <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap-theme.min.css">
    

    <body>



      <nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">isItCancelled?!?</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul id='searchUL' class="nav navbar-nav">
      {% if not user.is_authenticated %}
        <li class="active"><a href="{%url 'registerPage' %}">Register <span class="sr-only">(current)</span></a></li>
        
        <li><a href="{% url 'hack.views.signin'%}">Login</a></li>
        {% endif %}
        {% if user.is_authenticated %}
        <!-- <li><a href="{% url 'hack.views.notify'%}">Notify</a></li> -->
        <li><a href="{% url 'hack.views.addClass'%}">Classes List</a></li>
        {% endif %}
          
      </ul>
      
      <ul  class="nav navbar-nav navbar-right">

        <!-- <li><a href="#">Link</a></li> -->
          {% if user.is_authenticated %}
          <li><a>Hello {{user}}</a></li>
          <li><a href="{% url 'logoutUser' %}">Logout</a></li>
          {% endif %}
          
          <li><a href="{% url 'userFeed' %}">Feed</a></li>

          </ul>
        
        
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- <form method="POST" action="{% url 'searchFeed' %}">
  <input class="form-control" style="float:left; width:200px" type="text" value="search box"/>
  <button type="submit" style="float:left" class="btn btn-success" value="Search">Search</button>
  </form> -->

<script type="text/javascript">
  
$(window).bind('load', function(){
  var url = window.location.href
    console.log(url)
    if (url=='http://localhost:8000/userFeed/'){
    // console.log("INSIDE")
  // <input class="form-control" style="float:left; width:200px" type="text" value="search box"/>  
  $('#searchUL').append('<form method="POST" style="margin-left:800px; margin-top:10px;" action="{% url "searchFeed" %}">  {{searchFeedForm.className}}  <button type="submit" class="btn btn-success" value="Search">Search</button> <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}" /> </form>')

// <input type='hidden' name='csrfmiddlewaretoken' value='u3s4hakN8hTUeAwOCbGfgYIvoUdzrHAM' /> </form>')



  }

})

</script>

 

app/hack/templates/landing.html
{% extends 'base.html' %}

app/hack/templates/notify.html
<!-- <!DOCTYPE html> -->
<!-- <html lang="en"> -->
<!-- <head> -->
<!-- <title>Notify</title> -->
<!-- </head> -->

{% include 'base.html' %}
<body>

{% if msg%}
<div class="alert alert-success alert-dismissable">
   <button type="button" class="close" data-dismiss="alert" 
      aria-hidden="true">
      &times;
   </button>
   {{msg}}
</div>
{% endif %}


{% if notifyMsg %}
<div class="alert alert-success alert-dismissable">
   <button type="button" class="close" data-dismiss="alert" 
      aria-hidden="true">
      &times;
   </button>
   {{notifyMsg}}
</div>
{% endif %}
	




	<form method="POST" action="{% url 'hack.views.sendNotification' %}">
	{% csrf_token %}
		<input type="button" id="notifyButton" data-toggle="modal" data-target="#notifyModal" value="notify" style="width:250px; height:100px"/>

	</form>

	<!-- <form method="POST" action="{% url 'hack.views.addNumbers' %}">
	{% csrf_token %}

		<input type="button" data-toggle="modal" data-target="#myModal" id="addNumbersButton" value="Add Numbers" style="width:250px; height:100px"/>
	</form> -->

		<input class="btn btn-primary"  type="button" data-toggle="modal" data-target="#myModal" id="addNumbersButton" value="Add Numbers"  style="width:250px; height:100px"/><!---->
		<!--<button class="btn btn-default" id="addNumbersButton" data-toggle="modal" data-target="#myModal">Add Numbers</button>-->
	</form>



	<!-- ADD NUMBERS MODAL -->
	<form method='POST' action="{% url 'addDetailsToDB' %}">
	{%csrf_token %}
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h4 class="modal-title" id="myModalLabel">Student Details</h4>
				</div>
				<div class="modal-body">
				<table>
				<tr>
				<td>
				Class Name:
				</td>
				<td>
				{{form.className}}
				</td>
				<tr>
				<td>
					<h5>Phone Numbers:</h5>
					{{form.phoneNumbers}}
				</td>
				<td style="margin-left:50px">
					<h5>Emails:</h5>
					{{form.emails}}
					</td>
					</tr>
					</table>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save Numbers</button>
				</div>
			</div>
		</div>
	</div>
	</form>
	<!-- END OF END NUMBERS MODAL -->



	<!-- NOTIFY MODAL -->
	<form method='POST' action="{% url 'sendNotification' %}">
	{%csrf_token %}
	<div class="modal fade" id="notifyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
					<h4 class="modal-title" id="myModalLabel">Student Details</h4>
				</div>
				<div class="modal-body">
				<table>
				<tr>
				<td>
				Class
				</td>
				<td>
				{{notifyForm.class_name}}
				</td>
				<tr>
				<td>
					<h5>Note:</h5>
					{{notifyForm.note}}
				</td>
				</tr>
				</table>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Send Notification</button>
				</div>
			</div>
		</div>
	</div>
	</form>
	<!-- END OF NOTIFY MODAL -->






	<!-- <form method="POST" action="{% url 'hack.views.logoutUser' %}">
	{% csrf_token %}

		<input type="submit" id="addNumbersButton" value="Logout" style="width:250px; height:100px"/>
	</form> -->

		<!---<input class="btn btn-default"  type="submit" id="logOut" value="Logout" style="width:250px; height:100px"/>-->
		<button class="btn btn-primary" id="logOut">Logout</button>
	</form>



	

</body>

</html>

app/hack/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title> Sign Up </title>
    <link rel="stylesheet" href="{{STATIC_URL}}/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{STATIC_URL}}/css/register.css">
    <link rel="stylesheet" href="{{STATIC_URL}}/css/body.css">
    <link rel="stylesheet" href="{{STATIC_URL}}/bootstrap/css/bootstrap-theme.min.css">
    <script type="text/javascript" src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>
</head>

<body>

	{% include 'base.html' %}
    
    <div class='container text-center'>
        <h2 class="form-signin-heading">Create Account</h2>
        <br>
    	<form class="form-signin" method="post" action="{% url 'hack.views.login' %}" role="form">
        {% csrf_token %}
        {% load bootstrap %}    

        <table>
        <tr>
           
            <td class="container text-center">{{ form.username | bootstrap_horizontal}}</td>
        </tr>
        

        <tr>
            
            <td class="container text-center">{{ form.password1 | bootstrap_horizontal }}</td>
        </tr>

        <tr>
       
            <td style="padding-top:40px" class="container text-center" >{{ form.password2 | bootstrap_horizontal }}</td>
        </tr>


        </table>
        {{msg}}

        <button class="btn btn-lg btn-primary" type="submit">Register</button>
        <input type="hidden" name="next" value="{{ next }}" />
        </form>
    </div>   


</body>







</html>

app/hack/templates/signin.html
{% include 'base.html' %}

<html lang="en">
<head>
    <title> Sign in </title>
    <link rel="stylesheet" href="{{STATIC_URL}}/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{STATIC_URL}}/css/body.css">
    <link rel="stylesheet" href="{{STATIC_URL}}/bootstrap/css/bootstrap-theme.min.css">
    <script type="text/javascript" src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>
</head>

<body>
<div class="container text-center">
<form class="form-signin" method="post" action="{% url 'hack.views.authenticateUser' %}" role="form">
{% csrf_token %}
{% load bootstrap %}
<h2 class="form-signin-heading">Sign In</h2> 
<table>
<tr>
    
    <td class="container text-center">{{form.username | bootstrap_horizontal}}</td>
</tr>

	<tr style="margin-top: 20px;">
   
    <td style="padding-top: 30px;" class="container text-center">{{form.password | bootstrap_horizontal}}</td>
</tr>
</table>
<br>
 <button style="margin-left:20px"class="btn btn-lg btn-primary" type="submit">Login</button>
</form>
</div>
{{msg}}
</body>

app/hack/templates/signup.html
{% include 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title> Is It Cancelled </title>
	<link type="text/css" href="{{STATIC_URL}}css/signup.css" rel="stylesheet">
</head>

<body>
	
<div class="bg-images text-center">
   
    
      <img class="img-responsive img-rounded center-block" src="{{STATIC_URL}}img/professor.jpg">
    
    
  </div>

</body>
</html>

app/hack/templates/studentView.html
<!-- <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
 -->
    <!-- <title>Professor</title> -->

    <!-- Bootstrap core CSS -->
    <!-- <link href="bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    <!-- <link href="studentView.css" rel="stylesheet"> -->

  <!-- </head> -->
  {% include 'base.html' %}
  <!-- <head> -->
    <!-- <link rel="stylesheet" href="{{STATIC_URL}}css/studentView.css"> -->
  <!-- </head> -->

  <body style="background-color: #5A7194;">
  <!-- nav bar for professor name, class, subscribe -->
 
   <!--
        <ul class="list-group">
            <li class="list-group-item"> Class is cancelled January 1st 
            <br>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac vestibulum velit. Duis id fringilla libero, ut volutpat eros. Pellentesque sed rhoncus sapien. Nullam non congue neque. Phasellus eget lacinia leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.  </li>
            
            <li class="list-group-item"> Class is cancelled January 1st  </li>

            <li class="list-group-item"> Class is cancelled January 1st  </li>
        </ul>
        -->

        {% for notif in notifications %}
       <div class="panel panel-default">
         <div class="panel-body">
           
            
            {{notif.class_name}}<br>
            {{notif.note}}
                <!-- Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac vestibulum velit. Duis id fringilla libero, ut volutpat eros. Pellentesque sed rhoncus sapien. Nullam non congue neque. Phasellus eget lacinia leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. -->
         </div>
         <!-- <div class="panel-footer">12:45 December 15</div> -->
         <div class="panel-footer">{{notif.timeStamp}}</div>
       </div>
       {% endfor %}

       <!-- <div class="panel panel-default">
         <div class="panel-body">
           Class is cancelled January 1st 
            <br>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac vestibulum velit. Duis id fringilla libero, ut volutpat eros. Pellentesque sed rhoncus sapien. Nullam non congue neque. Phasellus eget lacinia leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
         </div>
         <div class="panel-footer">12:45 December 15</div>
       </div>

 -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script> -->
    <!-- <script src="bootstrap/dist/js/bootstrap.min.js"></script> -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
  </body>
</html>